#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Problem 45 - Triangular, pentagonal, and hexagonal
==================================================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle    Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal  Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from utils.number import is_triangular, is_pentagonal, gen_hexagonal

for n in gen_hexagonal():
    if n == 1 or n == 40755:
        continue
    if is_triangular(n) and is_pentagonal(n):
        print(n)
        break

# Answer: 1533776805
