# -*- coding: utf-8 -*-
"""
Problem 12 - Highly divisible triangular number
===============================================

The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms
would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

def triangle(n):
    return n * (n + 1) / 2

def is_square(n):
    return n**0.5 == int(n**0.5)

def num_divisors(n):
    d = 0
    for i in xrange(int(n**0.5)):
        d += 2 if n % (i + 1) == 0 else 0
    return d - 1 if is_square(n) else d

n = 0
while (num_divisors(triangle(n)) < 500):
    n += 1
print triangle(n)

# Answer: 76576500
