# -*- coding: utf-8 -*-
"""
Problem 2 - Even Fibonacci numbers
==================================

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

a = 0
b = 2
sum = 0
while (b < 4000000):
    sum += b
    a, b = b, a + 4 * b
print sum

# Answer: 4613732
